# backend\app\services\ai\ai_service.py

from langchain_groq import ChatGroq

from app.core.load_env import GROQ_API_KEY,GROQ_MODEL
from app.schemas.response_schema import ResponseSchema


# Initialize the Groq LLM
llm = ChatGroq(
    api_key=GROQ_API_KEY,
    model=GROQ_MODEL,
    temperature=0.7
)

# Get AI Response from AI Model
def get_ai_response(prompt: str) -> ResponseSchema:
    try:
        messages = [
            ("system", "You are a helpful assistant."),
            ("human", prompt)
        ]

        ai_response = llm.invoke(messages)
        response = getattr(ai_response, "content", str(ai_response))
        
        if not response:
            return ResponseSchema(
                status=False,
                message="No response generated by the AI model.",
                data=None
            )
        
        return ResponseSchema(
            status=True,
            message="AI response generated successfully.",
            data=response
        )
    
    except Exception as e:
        return ResponseSchema(
            status=False,
            message=f"Error generating AI response: {str(e)}",
            data=None
        )
    
    

